In [10]:
import numpy as np
docs=[
    'go pakistan',
    'pakistan pakistan',
    'jeetega jbhai jeetega bhai jeetega',
    'pakistan zindabad ki jai',
    'kohli kohli',
    'sachin tendulkar',
    'dhoni dhoni',
    'sohal khan ki jai',
    'inquilab zindabad'
]

In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(oov_token='<nothing>')


In [12]:
tokenizer.fit_on_texts(docs)

In [13]:
tokenizer.word_index

{'<nothing>': 1,
 'pakistan': 2,
 'jeetega': 3,
 'zindabad': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'dhoni': 8,
 'go': 9,
 'jbhai': 10,
 'bhai': 11,
 'sachin': 12,
 'tendulkar': 13,
 'sohal': 14,
 'khan': 15,
 'inquilab': 16}

In [14]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('pakistan', 4),
             ('jeetega', 3),
             ('jbhai', 1),
             ('bhai', 1),
             ('zindabad', 2),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 1),
             ('tendulkar', 1),
             ('dhoni', 2),
             ('sohal', 1),
             ('khan', 1),
             ('inquilab', 1)])

In [46]:
tokenizer.document_counts

AttributeError: 'Tokenizer' object has no attribute 'document_counts'

In [18]:
sequences=tokenizer.texts_to_sequences(docs)
sequences

[[9, 2],
 [2, 2],
 [3, 10, 3, 11, 3],
 [2, 4, 5, 6],
 [7, 7],
 [12, 13],
 [8, 8],
 [14, 15, 5, 6],
 [16, 4]]

In [19]:
from keras.utils import pad_sequences

In [20]:
sequences=pad_sequences(sequences,padding='post')

In [21]:
sequences

array([[ 9,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 3, 10,  3, 11,  3],
       [ 2,  4,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [12, 13,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  5,  6,  0],
       [16,  4,  0,  0,  0]], dtype=int32)

In [ ]:

# Embedding
docs=[
    'go pakistan',
    'pakistan pakistan',
    'jeetega jbhai jeetega bhai jeetega',
    'pakistan zindabad ki jai',
    'kohli kohli',
    'sachin tendulkar',
    'dhoni dhoni',
    'sohal khan ki jai',
    'inquilab zindabad'
]

In [26]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()

In [27]:
tokenizer.fit_on_texts(docs)

In [28]:
len(tokenizer.word_index)

15

In [29]:
sequences=tokenizer.texts_to_sequences(docs)
sequences

[[8, 1],
 [1, 1],
 [2, 9, 2, 10, 2],
 [1, 3, 4, 5],
 [6, 6],
 [11, 12],
 [7, 7],
 [13, 14, 4, 5],
 [15, 3]]

In [30]:
from keras.utils import pad_sequences
sequences=pad_sequences(sequences,padding='post')
sequences

array([[ 8,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 2,  9,  2, 10,  2],
       [ 1,  3,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [11, 12,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [13, 14,  4,  5,  0],
       [15,  3,  0,  0,  0]], dtype=int32)

In [45]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten
model=Sequential()
model.add(Embedding(19,output_dim=2,input_length=5))
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.compile('adam','accuracy')

In [44]:
pred=model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step
[[[ 0.04205865  0.02101029]
  [ 0.00665085  0.0221884 ]
  [-0.03205364 -0.01569351]
  [-0.03205364 -0.01569351]
  [-0.03205364 -0.01569351]]

 [[ 0.00665085  0.0221884 ]
  [ 0.00665085  0.0221884 ]
  [-0.03205364 -0.01569351]
  [-0.03205364 -0.01569351]
  [-0.03205364 -0.01569351]]

 [[ 0.02415365 -0.03075647]
  [ 0.03753186  0.01129181]
  [ 0.02415365 -0.03075647]
  [-0.04059387  0.02926696]
  [ 0.02415365 -0.03075647]]

 [[ 0.00665085  0.0221884 ]
  [-0.03841985  0.0193353 ]
  [ 0.04740709 -0.04712545]
  [ 0.04005451 -0.0143039 ]
  [-0.03205364 -0.01569351]]

 [[ 0.00228234 -0.00169461]
  [ 0.00228234 -0.00169461]
  [-0.03205364 -0.01569351]
  [-0.03205364 -0.01569351]
  [-0.03205364 -0.01569351]]

 [[ 0.04962576  0.03266956]
  [-0.04044396  0.04364507]
  [-0.03205364 -0.01569351]
  [-0.03205364 -0.01569351]
  [-0.03205364 -0.01569351]]

 [[ 0.02623082 -0.04598865]
  [ 0.02623082 -0.04598865]
  [-0.03205364 -0.01569351]
  [-0.03205364 -0.0156935